pub mod array;
pub mod bit_set;
pub mod block_hit_result;
pub mod chat;
pub mod chunk;
pub mod chunk_pos;
pub mod client_information;
pub mod component_changes;
pub mod entity_metadata;
pub mod game_profile;
pub mod global_pos;
pub mod identifier;
pub mod instant;
pub mod int_list;
pub mod item_stack_hash;
pub mod light;
pub mod main_hand;
pub mod math;
pub mod particle;
pub mod player_spawn_info;
pub mod position;
pub mod resolvable_profile;
pub mod slot;
pub mod sound;
pub mod teleport_flags;
pub mod untrusted_slot;
pub mod var_int;
pub mod var_long;
pub mod velocity;

pub use array::Array;
pub use bit_set::BitSet;
pub use block_hit_result::BlockHitResult;
pub use chunk_pos::ChunkPos;
pub use client_information::ClientInformation;
pub use component_changes::ComponentChanges;
pub use global_pos::GlobalPos;
pub use instant::NetworkInstant;
pub use int_list::IntList;
pub use item_stack_hash::{ItemStackHash, ItemStackHashComponent};
pub use main_hand::MainHand;
pub use math::{Quaternionf, Vector3d, Vector3f};
pub use particle::{Particle, ParticlePayload, VibrationParticlePayload};
pub use player_spawn_info::CommonPlayerSpawnInfo;
pub use position::Position;
pub use resolvable_profile::{
    PartialGameProfile, PlayerSkinPatch, ResolvableProfile, ResolvableProfileIdentity,
};
pub use slot::Slot;
pub use spinel_registry::Identifier;
pub use teleport_flags::TeleportFlags;
pub use untrusted_slot::UntrustedSlot;
pub use var_int::VarInt;
pub use var_long::VarLong;
pub use velocity::Velocity;

pub type ByteArray = Array<i8>;
pub type ContainerId = i32;
pub type FixedBitSet = BitSet;
pub type LongArray = Array<i64>;
pub type Optional<T> = Option<T>;
pub type PublicKey = ByteArray;
pub type UnsignedByte = u8;
pub type UnsignedShort = u16;
pub type VarIntArray = IntList;
#[cfg(test)]
mod tests;
