mod abstract_display_meta;
mod abstract_fish_meta;
mod abstract_golem_meta;
mod abstract_horse_meta;
mod abstract_illager_meta;
mod abstract_minecart_container_meta;
mod abstract_minecart_meta;
mod abstract_nautilus_meta;
mod abstract_skeleton_meta;
mod abstract_vehicle_meta;
mod abstract_villager_meta;
mod ageable_mob_meta;
mod ageable_water_animal_meta;
mod allay_meta;
mod ambient_creature_meta;
mod animal_meta;
mod aquatic;
mod area_effect_cloud_meta;
mod armadillo_meta;
mod armor_stand_meta;
mod avatar_meta;
mod axolotl_meta;
mod base_piglin_meta;
mod bat_meta;
mod bee_meta;
mod blaze_meta;
mod block_display_meta;
mod boat_meta;
mod bogged_meta;
mod camel_husk_meta;
mod camel_meta;
mod cat_meta;
mod cave_spider_meta;
mod chest_minecart_meta;
mod chested_horse_meta;
mod chicken_meta;
mod command_block_minecart_meta;
mod copper_golem_meta;
mod cow_meta;
mod creaking_meta;
mod creeper_meta;
mod definition;
pub mod definitions;
mod dolphin_meta;
mod donkey_meta;
mod drowned_meta;
mod end_crystal_meta;
mod ender_dragon_meta;
mod enderman_meta;
mod entity_meta;
mod entity_meta_cast;
mod entity_meta_ref;
mod entity_metadata;
mod evoker_meta;
mod falling_block_meta;
mod fishing_hook_meta;
mod flying_meta;
mod fox_meta;
mod frog_meta;
mod furnace_minecart_meta;
mod ghast_meta;
mod goat_meta;
mod golem;
mod guardian_meta;
mod hanging_meta;
mod happy_ghast_meta;
mod hoglin_meta;
mod holder;
mod hopper_minecart_meta;
mod horse_meta;
mod hostile;
mod husk_meta;
mod illusioner_meta;
mod interaction_meta;
mod iron_golem_meta;
mod item_display_meta;
mod item_frame_meta;
mod living_entity_meta;
mod living_entity_meta_ref;
mod llama_meta;
mod magma_cube_meta;
mod minecart_meta;
mod mob_meta;
mod monster_meta;
mod mooshroom_meta;
mod mule_meta;
mod nautilus_meta;
mod ocelot_meta;
mod ominous_item_spawner_meta;
mod painting_meta;
mod panda_meta;
mod parrot_meta;
mod pathfinder_mob_meta;
mod phantom_meta;
mod pig_meta;
mod piglin_brute_meta;
mod piglin_meta;
mod pillager_meta;
mod player_meta;
mod polar_bear_meta;
mod primed_tnt_meta;
mod pufferfish_meta;
mod rabbit_meta;
mod raider_meta;
mod ravager_meta;
mod salmon_meta;
mod sheep_meta;
mod shulker_meta;
mod skeleton_horse_meta;
mod slime_meta;
mod sniffer_meta;
mod snow_golem_meta;
mod spawner_minecart_meta;
mod spellcaster_illager_meta;
mod spider_meta;
mod strider_meta;
mod tameable_animal_meta;
mod terrestrial;
mod text_display_meta;
mod tnt_minecart_meta;
mod tropical_fish_meta;
mod turtle_meta;
mod vex_meta;
mod villager;
mod villager_meta;
mod vindicator_meta;
mod warden_meta;
mod water_animal_meta;
mod witch_meta;
mod wither_meta;
mod wolf_meta;
mod zoglin_meta;
mod zombie_horse_meta;
mod zombie_meta;
mod zombie_nautilus_meta;
mod zombie_villager_meta;
mod zombified_piglin_meta;

pub use abstract_display_meta::{AbstractDisplayMeta, BillboardConstraints};
pub use abstract_fish_meta::AbstractFishMeta;
pub use abstract_golem_meta::AbstractGolemMeta;
pub use abstract_horse_meta::AbstractHorseMeta;
pub use abstract_illager_meta::AbstractIllagerMeta;
pub use abstract_minecart_container_meta::AbstractMinecartContainerMeta;
pub use abstract_minecart_meta::AbstractMinecartMeta;
pub use abstract_nautilus_meta::AbstractNautilusMeta;
pub use abstract_skeleton_meta::AbstractSkeletonMeta;
pub use abstract_vehicle_meta::AbstractVehicleMeta;
pub use abstract_villager_meta::AbstractVillagerMeta;
pub use ageable_mob_meta::AgeableMobMeta;
pub use ageable_water_animal_meta::AgeableWaterAnimalMeta;
pub use allay_meta::AllayMeta;
pub use ambient_creature_meta::AmbientCreatureMeta;
pub use animal_meta::AnimalMeta;
pub use aquatic::{PufferfishState, TropicalFishVariant};
pub use area_effect_cloud_meta::AreaEffectCloudMeta;
pub use armadillo_meta::ArmadilloMeta;
pub use armor_stand_meta::ArmorStandMeta;
pub use avatar_meta::AvatarMeta;
pub use axolotl_meta::AxolotlMeta;
pub use base_piglin_meta::BasePiglinMeta;
pub use bat_meta::BatMeta;
pub use bee_meta::BeeMeta;
pub use blaze_meta::BlazeMeta;
pub use block_display_meta::BlockDisplayMeta;
pub use boat_meta::BoatMeta;
pub use bogged_meta::BoggedMeta;
pub use camel_husk_meta::CamelHuskMeta;
pub use camel_meta::CamelMeta;
pub use cat_meta::CatMeta;
pub use cave_spider_meta::CaveSpiderMeta;
pub use chest_minecart_meta::ChestMinecartMeta;
pub use chested_horse_meta::ChestedHorseMeta;
pub use chicken_meta::ChickenMeta;
pub use command_block_minecart_meta::CommandBlockMinecartMeta;
pub use copper_golem_meta::CopperGolemMeta;
pub use cow_meta::CowMeta;
pub use creaking_meta::CreakingMeta;
pub use creeper_meta::CreeperMeta;
pub use definition::{MetadataBitMaskDefinition, MetadataByteMaskDefinition, MetadataDefinition};
pub use dolphin_meta::DolphinMeta;
pub use donkey_meta::DonkeyMeta;
pub use drowned_meta::DrownedMeta;
pub use end_crystal_meta::EndCrystalMeta;
pub use ender_dragon_meta::{EnderDragonMeta, EnderDragonPhase};
pub use enderman_meta::EndermanMeta;
pub use entity_meta::EntityMeta;
pub use entity_meta_cast::EntityMetaCast;
pub use entity_meta_ref::EntityMetaRef;
pub use entity_metadata::{
    EntityMetadata, EntityMetadataRef, LivingEntityMetadata, LivingEntityMetadataRef,
};
pub use evoker_meta::EvokerMeta;
pub use falling_block_meta::FallingBlockMeta;
pub use fishing_hook_meta::FishingHookMeta;
pub use flying_meta::FlyingMeta;
pub use fox_meta::FoxMeta;
pub use frog_meta::FrogMeta;
pub use furnace_minecart_meta::FurnaceMinecartMeta;
pub use ghast_meta::GhastMeta;
pub use goat_meta::GoatMeta;
pub use golem::{CopperGolemState, CopperGolemWeatherState};
pub use guardian_meta::GuardianMeta;
pub use hanging_meta::HangingMeta;
pub use happy_ghast_meta::HappyGhastMeta;
pub use hoglin_meta::HoglinMeta;
pub use holder::MetadataHolder;
pub use hopper_minecart_meta::HopperMinecartMeta;
pub use horse_meta::HorseMeta;
pub use hostile::{CreeperState, SpellcasterIllagerSpell};
pub use husk_meta::HuskMeta;
pub use illusioner_meta::IllusionerMeta;
pub use interaction_meta::InteractionMeta;
pub use iron_golem_meta::IronGolemMeta;
pub use item_display_meta::{DisplayContext, ItemDisplayMeta};
pub use item_frame_meta::ItemFrameMeta;
pub use living_entity_meta::LivingEntityMeta;
pub use living_entity_meta_ref::LivingEntityMetaRef;
pub use llama_meta::LlamaMeta;
pub use magma_cube_meta::MagmaCubeMeta;
pub use minecart_meta::MinecartMeta;
pub use mob_meta::MobMeta;
pub use monster_meta::MonsterMeta;
pub use mooshroom_meta::MooshroomMeta;
pub use mule_meta::MuleMeta;
pub use nautilus_meta::NautilusMeta;
pub use ocelot_meta::OcelotMeta;
pub use ominous_item_spawner_meta::OminousItemSpawnerMeta;
pub use painting_meta::PaintingMeta;
pub use panda_meta::PandaMeta;
pub use parrot_meta::ParrotMeta;
pub use pathfinder_mob_meta::PathfinderMobMeta;
pub use phantom_meta::PhantomMeta;
pub use pig_meta::PigMeta;
pub use piglin_brute_meta::PiglinBruteMeta;
pub use piglin_meta::PiglinMeta;
pub use pillager_meta::PillagerMeta;
pub use player_meta::PlayerMeta;
pub use polar_bear_meta::PolarBearMeta;
pub use primed_tnt_meta::PrimedTntMeta;
pub use pufferfish_meta::PufferfishMeta;
pub use rabbit_meta::RabbitMeta;
pub use raider_meta::RaiderMeta;
pub use ravager_meta::RavagerMeta;
pub use salmon_meta::SalmonMeta;
pub use sheep_meta::SheepMeta;
pub use shulker_meta::ShulkerMeta;
pub use skeleton_horse_meta::SkeletonHorseMeta;
pub use slime_meta::SlimeMeta;
pub use sniffer_meta::SnifferMeta;
pub use snow_golem_meta::SnowGolemMeta;
pub use spawner_minecart_meta::SpawnerMinecartMeta;
pub use spellcaster_illager_meta::SpellcasterIllagerMeta;
pub use spider_meta::SpiderMeta;
pub use spinel_registry::{
    AxolotlVariant, FoxVariant, HorseColor, LlamaVariant, MooshroomVariant, ParrotColor,
    RabbitVariant, SalmonSize, TropicalFishPattern,
};
pub use strider_meta::StriderMeta;
pub use tameable_animal_meta::TameableAnimalMeta;
pub use terrestrial::{ArmadilloState, HorseMarking, HorseVariant, PandaGene, SnifferState};
pub use text_display_meta::{TextAlignment, TextDisplayMeta};
pub use tnt_minecart_meta::TntMinecartMeta;
pub use tropical_fish_meta::TropicalFishMeta;
pub use turtle_meta::TurtleMeta;
pub use vex_meta::VexMeta;
pub use villager::{VillagerData, VillagerLevel};
pub use villager_meta::VillagerMeta;
pub use vindicator_meta::VindicatorMeta;
pub use warden_meta::WardenMeta;
pub use water_animal_meta::WaterAnimalMeta;
pub use witch_meta::WitchMeta;
pub use wither_meta::WitherMeta;
pub use wolf_meta::WolfMeta;
pub use zoglin_meta::ZoglinMeta;
pub use zombie_horse_meta::ZombieHorseMeta;
pub use zombie_meta::ZombieMeta;
pub use zombie_nautilus_meta::ZombieNautilusMeta;
pub use zombie_villager_meta::ZombieVillagerMeta;
pub use zombified_piglin_meta::ZombifiedPiglinMeta;
#[cfg(test)]
mod tests;
