pub mod clear_dialog;
pub mod code_of_conduct;
pub mod cookie_request;
pub mod custom_report_details;
pub mod disconnect;
pub mod features;
pub mod finish_configuration;
pub mod keep_alive;
pub mod known_packs;
pub mod ping;
pub mod plugin_message;
pub mod registry_data;
pub mod registry_entry;
pub mod reset_chat;
pub mod resource_pack_pop;
pub mod resource_pack_push;
pub mod server_links;
pub mod show_dialog;
pub mod store_cookie;
#[cfg(test)]
mod tests;
pub mod transfer;
pub mod update_tags;
