#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BlockEntityType {
    Furnace,
    Chest,
    TrappedChest,
    EnderChest,
    Jukebox,
    Dispenser,
    Dropper,
    Sign,
    HangingSign,
    MobSpawner,
    CreakingHeart,
    Piston,
    BrewingStand,
    EnchantingTable,
    EndPortal,
    Beacon,
    Skull,
    DaylightDetector,
    Hopper,
    Comparator,
    Banner,
    StructureBlock,
    EndGateway,
    CommandBlock,
    ShulkerBox,
    Bed,
    Conduit,
    Barrel,
    Smoker,
    BlastFurnace,
    Lectern,
    Bell,
    Jigsaw,
    Campfire,
    Beehive,
    SculkSensor,
    CalibratedSculkSensor,
    SculkCatalyst,
    SculkShrieker,
    ChiseledBookshelf,
    Shelf,
    BrushableBlock,
    DecoratedPot,
    Crafter,
    TrialSpawner,
    Vault,
    TestBlock,
    TestInstanceBlock,
    CopperGolemStatue,
}

impl BlockEntityType {
    pub const ALL: [Self; 49] = [
        Self::Furnace,
        Self::Chest,
        Self::TrappedChest,
        Self::EnderChest,
        Self::Jukebox,
        Self::Dispenser,
        Self::Dropper,
        Self::Sign,
        Self::HangingSign,
        Self::MobSpawner,
        Self::CreakingHeart,
        Self::Piston,
        Self::BrewingStand,
        Self::EnchantingTable,
        Self::EndPortal,
        Self::Beacon,
        Self::Skull,
        Self::DaylightDetector,
        Self::Hopper,
        Self::Comparator,
        Self::Banner,
        Self::StructureBlock,
        Self::EndGateway,
        Self::CommandBlock,
        Self::ShulkerBox,
        Self::Bed,
        Self::Conduit,
        Self::Barrel,
        Self::Smoker,
        Self::BlastFurnace,
        Self::Lectern,
        Self::Bell,
        Self::Jigsaw,
        Self::Campfire,
        Self::Beehive,
        Self::SculkSensor,
        Self::CalibratedSculkSensor,
        Self::SculkCatalyst,
        Self::SculkShrieker,
        Self::ChiseledBookshelf,
        Self::Shelf,
        Self::BrushableBlock,
        Self::DecoratedPot,
        Self::Crafter,
        Self::TrialSpawner,
        Self::Vault,
        Self::TestBlock,
        Self::TestInstanceBlock,
        Self::CopperGolemStatue,
    ];

    #[must_use]
    pub const fn id(self) -> i32 {
        self as i32
    }

    #[must_use]
    pub fn from_id(id: i32) -> Option<Self> {
        Self::ALL.get(id as usize).copied()
    }

    #[must_use]
    pub const fn key(self) -> &'static str {
        match self {
            Self::Furnace => "furnace",
            Self::Chest => "chest",
            Self::TrappedChest => "trapped_chest",
            Self::EnderChest => "ender_chest",
            Self::Jukebox => "jukebox",
            Self::Dispenser => "dispenser",
            Self::Dropper => "dropper",
            Self::Sign => "sign",
            Self::HangingSign => "hanging_sign",
            Self::MobSpawner => "mob_spawner",
            Self::CreakingHeart => "creaking_heart",
            Self::Piston => "piston",
            Self::BrewingStand => "brewing_stand",
            Self::EnchantingTable => "enchanting_table",
            Self::EndPortal => "end_portal",
            Self::Beacon => "beacon",
            Self::Skull => "skull",
            Self::DaylightDetector => "daylight_detector",
            Self::Hopper => "hopper",
            Self::Comparator => "comparator",
            Self::Banner => "banner",
            Self::StructureBlock => "structure_block",
            Self::EndGateway => "end_gateway",
            Self::CommandBlock => "command_block",
            Self::ShulkerBox => "shulker_box",
            Self::Bed => "bed",
            Self::Conduit => "conduit",
            Self::Barrel => "barrel",
            Self::Smoker => "smoker",
            Self::BlastFurnace => "blast_furnace",
            Self::Lectern => "lectern",
            Self::Bell => "bell",
            Self::Jigsaw => "jigsaw",
            Self::Campfire => "campfire",
            Self::Beehive => "beehive",
            Self::SculkSensor => "sculk_sensor",
            Self::CalibratedSculkSensor => "calibrated_sculk_sensor",
            Self::SculkCatalyst => "sculk_catalyst",
            Self::SculkShrieker => "sculk_shrieker",
            Self::ChiseledBookshelf => "chiseled_bookshelf",
            Self::Shelf => "shelf",
            Self::BrushableBlock => "brushable_block",
            Self::DecoratedPot => "decorated_pot",
            Self::Crafter => "crafter",
            Self::TrialSpawner => "trial_spawner",
            Self::Vault => "vault",
            Self::TestBlock => "test_block",
            Self::TestInstanceBlock => "test_instance_block",
            Self::CopperGolemStatue => "copper_golem_statue",
        }
    }
}
